#!/usr/bin/env bash
# ============================================================================
# NPL MIS Portal — one-command local development setup.
#
#   bun run setup:local            (or: bash scripts/setup-local.sh)
#
# Performs, in order:
#   1. verify the runtime (bun ≥ 1.1)
#   2. create .env with working LOCAL values (never overwrites an existing one)
#   3. start the local stack (PostgreSQL 17 + realtime via docker-compose.dev.yml)
#      — or continue against an already-reachable external PostgreSQL
#   4. generate the Prisma client
#   5. verify database connectivity (real SELECT 1 — catches wrong credentials)
#   6. apply committed migrations (prisma migrate deploy — non-destructive)
#   7. seed demo data ONLY when the database is completely empty
#   8. sanity-check the environment and print the next command(s)
#
# Never requires AWS, Coolify or SMTP. Never runs destructive database
# commands (no migrate reset, no db push — seeding only happens on an empty
# database; skip entirely with SKIP_SEED=1 or --skip-seed).
# ============================================================================
set -euo pipefail

cd "$(cd "$(dirname "$0")/.." && pwd)"

# ---------------------------------------------------------------- helpers ---
BOLD='' GREEN='' YELLOW='' RED=''
if [ -t 1 ]; then
  BOLD='\033[1m' GREEN='\033[32m' YELLOW='\033[33m' RED='\033[31m'
fi
CLEAR='\033[0m'
step()  { printf "\n${BOLD}[%s] %s${CLEAR}\n" "$(date +%H:%M:%S)" "$1"; }
info()  { printf "  %s\n" "$1"; }
good()  { printf "  ${GREEN}✓ %s${CLEAR}\n" "$1"; }
warn()  { printf "  ${YELLOW}⚠ %s${CLEAR}\n" "$1"; }
die()   { printf "  ${RED}✗ %s${CLEAR}\n" "$1"; exit 1; }

SKIP_SEED=0
DID_SEED=0
for arg in "$@"; do
  case "$arg" in
    --skip-seed) SKIP_SEED=1 ;;
    *) die "unknown option: $arg (supported: --skip-seed)" ;;
  esac
done

printf "${BOLD}NPL MIS Portal — local development setup${CLEAR}\n"

# ------------------------------------------------- 1. runtime ---------------
step "1/8 Checking the runtime"

if ! command -v bun >/dev/null 2>&1; then
  die "bun is not installed. Install it first: https://bun.sh/docs/installation"
fi
BUN_VERSION="$(bun --version)"
good "bun ${BUN_VERSION}"
case "$BUN_VERSION" in
  0.*|1.0.*) die "bun ≥ 1.1 required (found ${BUN_VERSION})" ;;
esac

if [ ! -d node_modules ]; then
  step "Installing dependencies (bun install)"
  bun install --frozen-lockfile || die "bun install failed"
  good "dependencies installed"
else
  good "dependencies present (node_modules)"
fi

# ------------------------------------------------- 2. environment file ------
step "2/8 Preparing the environment file (.env)"

gen_secret() { # gen_secret <bytes> <encoding>
  if command -v openssl >/dev/null 2>&1; then
    if [ "$2" = "base64" ]; then openssl rand -base64 "$1" | tr -d '\n'
    else openssl rand -hex "$1"; fi
  else
    bun -e "console.log(require('node:crypto').randomBytes($1).toString('$2'))"
  fi
}

if [ -f .env ]; then
  # Validate the required local variables are present (values are not printed).
  MISSING=""
  for var in DATABASE_URL AUTH_SECRET REALTIME_SECRET; do
    val="$(grep -E "^${var}=" .env | tail -1 | cut -d= -f2- | tr -d '"' | tr -d "'")"
    [ -z "$val" ] && MISSING="${MISSING} ${var}"
  done
  if [ -n "$MISSING" ]; then
    die "existing .env is missing required variables:${MISSING}.
     Either fill them in (see .env.example) or rename .env away and re-run setup to regenerate a local one."
  fi
  good ".env exists (required variables present — values not shown)"
else
  AUTH_SECRET_VAL="$(gen_secret 32 base64)"
  REALTIME_SECRET_VAL="$(gen_secret 24 hex)"
  cat > .env <<EOF
# NPL MIS Portal — LOCAL DEVELOPMENT environment (generated by setup:local).
# Full annotated reference: .env.example   |   Docs: docs/local-development.md
# This file is git-ignored — never commit real secrets.

# Local PostgreSQL from docker-compose.dev.yml (loopback only)
DATABASE_URL=postgresql://npl:npl_dev_password@127.0.0.1:5432/npl_mis

# Session cookie signing key (generated locally, 32 random bytes)
AUTH_SECRET=${AUTH_SECRET_VAL}

# Realtime service wiring (the stack started by this script)
REALTIME_SECRET=${REALTIME_SECRET_VAL}
REALTIME_URL=http://127.0.0.1:3004
REALTIME_PUBLIC_URL=http://localhost:3003

# Optional extras — see .env.example:
# APP_URL=
# SMTP_HOST=
# MIGRATE_ON_START=true
# QUERY_LOG=
EOF
  chmod 600 .env
  good ".env created with locally generated secrets (AUTH_SECRET, REALTIME_SECRET)"
fi

# Export the .env values into THIS shell so child commands (prisma, seed,
# tests) use them even if the interactive shell exports stale values.
set -a
# shellcheck disable=SC1091
. ./.env
set +a

# ------------------------------------------------- 3. local database --------
step "3/8 Starting the local stack (PostgreSQL 17 + realtime)"

DB_HOST="$(printf '%s' "$DATABASE_URL" | sed -E 's#^[a-z]+://([^@]+@)?([^:/]+).*#\2#')"
DB_PORT="$(printf '%s' "$DATABASE_URL" | sed -nE 's#^[a-z]+://([^@]+@)?[^:/]+:([0-9]+).*#\2#p')"
[ -z "$DB_PORT" ] && DB_PORT=5432

STACK_MODE=""
if command -v docker >/dev/null 2>&1 && docker info >/dev/null 2>&1 && docker compose version >/dev/null 2>&1; then
  docker compose -f docker-compose.dev.yml up -d || die "failed to start the local stack.
     Check: docker compose -f docker-compose.dev.yml logs"
  good "docker stack started (postgres + realtime)"
  STACK_MODE="docker"
else
  # No Docker — continue only if the configured PostgreSQL is already reachable
  # (e.g. an externally installed instance).
  if (exec 3<>"/dev/tcp/${DB_HOST}/${DB_PORT}") 2>/dev/null; then
    exec 3>&- 3<&- || true
    warn "Docker is not available — continuing against the existing PostgreSQL at ${DB_HOST}:${DB_PORT}"
    warn "(the realtime service is not started by this script; start it with: cd mini-services/realtime && bun --hot index.ts)"
    STACK_MODE="external"
  else
    die "Docker is not available and nothing is listening at ${DB_HOST}:${DB_PORT}.
     Install Docker (https://docs.docker.com/get-docker/) so this script can start the local
     PostgreSQL + realtime stack, or point DATABASE_URL in .env at an already-running PostgreSQL."
  fi
fi

# ------------------------------------------------- 4. prisma client --------
step "4/8 Generating the Prisma client"
bun run db:generate >/dev/null || die "prisma generate failed"
good "Prisma client generated"

# ------------------------------------------------- 5. db connectivity ------
step "5/8 Verifying database connectivity"
# Retried for up to ~60s: a freshly created postgres container takes a few
# seconds to initialize before it accepts connections.
DB_PROBE=""
for i in $(seq 1 30); do
  DB_PROBE="$(bun -e '
    const { PrismaClient } = await import("@prisma/client")
    const db = new PrismaClient()
    try { await db.$queryRaw`SELECT 1`; console.log("OK") }
    catch (e) { console.log("FAIL " + String(e.message).split("\n")[0]) }
    finally { await db.$disconnect() }
  ' 2>/dev/null || echo "FAIL script error")"
  [ "$DB_PROBE" = "OK" ] && break
  sleep 2
done
case "$DB_PROBE" in
  OK) good "database reachable (SELECT 1${STACK_MODE:+, attempt $i})" ;;
  *) die "cannot query the database (${DB_PROBE}).
     Check DATABASE_URL in .env — wrong host, port or credentials?" ;;
esac

# ------------------------------------------------- 6. migrations -----------
step "6/8 Applying committed migrations (non-destructive)"
bun run db:deploy || die "migrations failed (is DATABASE_URL pointing at the local stack?)"
good "database schema is up to date"

# ------------------------------------------------- 7. seed (only if empty) -
step "7/8 Checking whether demo data is needed"

SEED_NOTE="skipped (database already had data)"
if [ "$SKIP_SEED" = "1" ]; then
  SEED_NOTE="skipped by request (--skip-seed / SKIP_SEED=1)"
  info "$SEED_NOTE"
else
  COUNTS="$(bun -e '
    const { PrismaClient } = await import("@prisma/client")
    const db = new PrismaClient()
    try {
      const users = await db.user.count()
      const records = await db.misRecord.count()
      console.log(`${users} ${records}`)
    } finally { await db.$disconnect() }
  ' 2>/dev/null || echo "ERROR")"
  USERS_COUNT="${COUNTS% *}"
  RECORDS_COUNT="${COUNTS#* }"
  if [ "$COUNTS" = "ERROR" ]; then
    warn "could not read the database — seed skipped. If this is unexpected, run: bun run db:seed"
    SEED_NOTE="skipped (database not readable)"
  elif [ "$USERS_COUNT" = "0" ] && [ "$RECORDS_COUNT" = "0" ]; then
    info "database is empty → seeding demo data (development only)"
    bun run db:seed || die "seed failed"
    DID_SEED=1
    SEED_NOTE="seeded (demo users + field registry + sample records)"
    good "demo data seeded"
  else
    info "database already has data (users: ${USERS_COUNT}, records: ${RECORDS_COUNT}) — seed skipped (it is destructive)"
  fi
fi

# ------------------------------------------------- 8. summary --------------
step "8/8 Final checks"

case "$DATABASE_URL" in
  postgresql://*|postgres://*) good "DATABASE_URL is a PostgreSQL connection" ;;
  *) die "DATABASE_URL does not look like a PostgreSQL URL" ;;
esac

if [ "$STACK_MODE" = "docker" ] && curl -s -o /dev/null --max-time 3 http://127.0.0.1:3003/ 2>/dev/null; then
  good "realtime service is reachable on http://localhost:3003"
fi

printf "\n${BOLD}Local setup complete.${CLEAR}\n"
if [ "$STACK_MODE" = "docker" ]; then
  printf "  Database : PostgreSQL 17 on 127.0.0.1:5432 (docker volume npl_pgdata_dev)\n"
  printf "  Realtime : http://localhost:3003 (browser) · http://127.0.0.1:3004 (internal)\n"
else
  printf "  Database : external PostgreSQL at %s:%s (Docker not used)\n" "$DB_HOST" "$DB_PORT"
  printf "  Realtime : start manually if needed — cd mini-services/realtime && bun --hot index.ts\n"
fi
printf "  Seeding  : %s\n" "$SEED_NOTE"
printf "\n${BOLD}Start the application:${CLEAR}\n"
printf "  bun run dev            → http://localhost:3000\n"
if [ "$DID_SEED" = "1" ]; then
  printf "\n  Demo login (development only): admin@npl.com / Admin@123\n"
fi
printf "\n  Full walkthrough: docs/local-development.md\n"
printf "  Verify everything:  bun run verify        (typecheck · lint · unit · build)\n"
