#!/usr/bin/env bash
# ============================================================================
# NPL MIS Portal — static + unit verification (no services required).
#
#   bun run verify
#
# Runs, in order (fail-fast):
#   1. TypeScript  — tsc --noEmit (src; the build also enforces this)
#   2. ESLint      — eslint .
#   3. Unit tests  — business identity & normalization (46 checks)
#   4. Unit tests  — formula engine incl. injection safety (42 checks)
#   5. Production build (next build, standalone)
#
# For the server-dependent e2e suites use:  bun run verify:full
# (prerequisites: local stack up + seeded database — it manages its own server).
# ============================================================================
set -euo pipefail

cd "$(cd "$(dirname "$0")/.." && pwd)"

BOLD='' GREEN='' RED='' CLEAR=''
if [ -t 1 ]; then BOLD='\033[1m' GREEN='\033[32m' RED='\033[31m'; fi

STEP=""
STEP_START=0
FAILURES=0

begin() { STEP="$1"; STEP_START=$(date +%s); printf "\n${BOLD}▶ %s${CLEAR}\n" "$STEP"; }
done_ok() {
  local took=$(( $(date +%s) - STEP_START ))
  printf "  ${GREEN}✓ %s — passed (%ss)${CLEAR}\n" "$STEP" "$took"
}
fail() { FAILURES=$((FAILURES+1)); printf "  ${RED}✗ %s — FAILED${CLEAR}\n" "$STEP"; }

run() { # run <label> <command...>
  begin "$1"; shift
  if "$@"; then done_ok; else fail; return 1; fi
}

printf "${BOLD}NPL MIS Portal — verification${CLEAR}\n"

# Remove stale dev-server type artifacts — `next dev` generates .next/dev/types
# route validators that reference routes as they were DURING the dev session;
# after route changes they linger and break `tsc --noEmit` (production builds
# never read this directory; it is fully regenerated by the next `next dev`).
rm -rf .next/dev

run "TypeScript (tsc --noEmit)"            bun run typecheck
run "ESLint"                               bun run lint
run "Unit tests — business identity (46)"  bun run test
run "Unit tests — formula engine (42)"     bun run test:formula
run "Production build (next build)"        bun run build

printf "\n${BOLD}Verification summary${CLEAR}\n"
printf "  TypeScript   : ok\n"
printf "  ESLint       : ok\n"
printf "  Unit tests   : 46 business-key + 42 formula checks ok\n"
printf "  Build        : production standalone ok\n"
printf "  ${GREEN}ALL CHECKS PASSED${CLEAR}\n"
